# Generated by Django 3.2.1 on 2021-05-13 16:18

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('href', models.URLField()),
                ('description', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('href', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('href', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=300)),
                ('slug', models.CharField(max_length=300)),
                ('product_line', models.CharField(max_length=300)),
                ('departures_start_date', models.DateField(null=True)),
                ('departures_end_date', models.DateField(null=True)),
                ('description', models.CharField(max_length=2000)),
                ('structured_itineraries', models.CharField(max_length=2000, null=True)),
                ('details', jsonfield.fields.JSONField(default=dict)),
                ('images', jsonfield.fields.JSONField(default=dict)),
                ('site_links', models.URLField()),
                ('tour', models.CharField(max_length=300)),
                ('departures_href', models.URLField()),
                ('departures_list', django.contrib.postgres.fields.ArrayField(base_field=models.DateField(blank=True), blank=True, max_length=3000, size=None)),
                ('from_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('booking_company', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tours.company')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.category')),
            ],
        ),
        migrations.CreateModel(
            name='Geography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finish_country', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='finish_country', to='tours.country')),
                ('geograpy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.tour')),
                ('primary_country', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_country', to='tours.country')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.region')),
                ('start_country', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='start_country', to='tours.country')),
                ('visited_countries', models.ManyToManyField(blank=True, to='tours.Country')),
            ],
        ),
    ]
