# Generated by Django 3.2.1 on 2021-05-13 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tours.category'),
        ),
    ]
