# Generated by Django 3.2.1 on 2021-05-13 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_region_href'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='href',
            field=models.URLField(blank=True),
        ),
    ]
