# Generated by Django 3.2.1 on 2021-05-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_country_href'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geography',
            old_name='geograpy',
            new_name='geography',
        ),
        migrations.AlterField(
            model_name='geography',
            name='visited_countries',
            field=models.ManyToManyField(blank=True, related_name='visited_countries', to='tours.Country'),
        ),
    ]
