# Generated by Django 3.2.1 on 2021-05-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_auto_20210514_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='category',
        ),
        migrations.AddField(
            model_name='tour',
            name='category',
            field=models.ManyToManyField(blank=True, to='tours.Category'),
        ),
    ]
