# Generated by Django 3.2.1 on 2021-05-14 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_auto_20210514_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='booking_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tours.company'),
        ),
    ]
