# Generated by Django 3.2.1 on 2021-05-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_alter_tour_booking_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='href',
            field=models.URLField(max_length=300),
        ),
    ]
