# Generated by Django 3.2.1 on 2021-05-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_alter_tour_href'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='site_links',
            field=models.JSONField(),
        ),
    ]
