# Generated by Django 3.2.1 on 2021-05-14 12:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0010_alter_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='departures_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(null=True), max_length=3000, null=True, size=None),
        ),
    ]
