# Generated by Django 3.2.1 on 2021-05-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0011_alter_tour_departures_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='from_price',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
    ]
