# Generated by Django 3.2.1 on 2021-05-14 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0012_alter_tour_from_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geography',
            name='primary_country',
        ),
    ]
