# Generated by Django 3.2.1 on 2021-05-14 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0013_remove_geography_primary_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geography',
            name='id',
        ),
        migrations.AlterField(
            model_name='geography',
            name='geography',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tours.tour'),
        ),
    ]
