# Generated by Django 3.2.1 on 2021-05-14 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0014_auto_20210514_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='finish_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finish_country', to='tours.country'),
        ),
        migrations.AddField(
            model_name='tour',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tours.region'),
        ),
        migrations.AddField(
            model_name='tour',
            name='start_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='start_country', to='tours.country'),
        ),
        migrations.AddField(
            model_name='tour',
            name='visited_countries',
            field=models.ManyToManyField(blank=True, related_name='visited_countries', to='tours.Country'),
        ),
        migrations.DeleteModel(
            name='Geography',
        ),
    ]
