# Generated by Django 3.2.1 on 2021-05-14 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0015_auto_20210514_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.region'),
        ),
    ]
