# Generated by Django 3.2.1 on 2021-05-17 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0016_alter_tour_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_group', to='tours.category'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='category_set', to='tours.Category'),
        ),
    ]
