# Generated by Django 3.2.1 on 2021-05-18 10:03

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0017_auto_20210517_1056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='structured_itineraries',
            new_name='structured_itinerary',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='tour',
        ),
        migrations.AddField(
            model_name='tour',
            name='itinerary',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
